### ISSUE TITLE
Update readme please

### ISSUE THREAD

**Issue by litnimax** [claudyus/dokku-odoo#2]
I could not run your dokku-odoo until did the the following:

dokku apps:create odoo
dokku plugin:install https://github.com/dokku/dokku-postgres.git
dokku postgres:create db
dokku postgres:link db odoo

But after doing git push dokku master I get the error:
```
       2017-12-29 05:40:34,603 1 INFO ? odoo: Odoo version 10.0-20171030
       2017-12-29 05:40:34,604 1 INFO ? odoo: Using configuration file at /etc/odoo/odoo.conf
       2017-12-29 05:40:34,604 1 INFO ? odoo: addons paths: ['/var/lib/odoo/addons/10.0', u'/mnt/extra-addons', u'/usr/lib/python2.7/dist-packages/odoo/addons']
       2017-12-29 05:40:34,604 1 INFO ? odoo: database: odoo@db:5432
    2017-12-29 05:40:34,608 1 INFO ? odoo.sql_db: Connection to the database failed
       Traceback (most recent call last):
         File "/usr/bin/odoo", line 9, in <module>
           odoo.cli.main()
         File "/usr/lib/python2.7/dist-packages/odoo/cli/command.py", line 64, in main
           o.run(args)
         File "/usr/lib/python2.7/dist-packages/odoo/cli/server.py", line 175, in run
           main(args)
         File "/usr/lib/python2.7/dist-packages/odoo/cli/server.py", line 140, in main
           odoo.service.db._create_empty_database(db_name)
         File "/usr/lib/python2.7/dist-packages/odoo/service/db.py", line 79, in _create_empty_database
           with closing(db.cursor()) as cr:
         File "/usr/lib/python2.7/dist-packages/odoo/sql_db.py", line 635, in cursor
           return Cursor(self.__pool, self.dbname, self.dsn, serialized=serialized)
         File "/usr/lib/python2.7/dist-packages/odoo/sql_db.py", line 177, in __init__
           self._cnx = pool.borrow(dsn)
         File "/usr/lib/python2.7/dist-packages/odoo/sql_db.py", line 518, in _locked
           return fun(self, *args, **kwargs)
         File "/usr/lib/python2.7/dist-packages/odoo/sql_db.py", line 586, in borrow
           **connection_info)
         File "/usr/lib/python2.7/dist-packages/psycopg2/__init__.py", line 164, in connect
           conn = _connect(dsn, connection_factory=connection_factory, async=async)
       psycopg2.OperationalError: could not translate host name "db" to address: Name or service not known
```

To solve it I had to do the following:

dokku config odoo
```
=====> odoo config vars
DATABASE_URL:                postgres://postgres:f22c80ed2d4d88eafacef691090311bd@dokku-postgres-db:5432/db
DOKKU_APP_TYPE:              dockerfile
DOKKU_DOCKERFILE_ENTRYPOINT: ENTRYPOINT ["/entrypoint.sh", "odoo"]
DOKKU_DOCKERFILE_PORTS:      8069/tcp 8071/tcp
```
I did the following:
```
dokku config:set odoo DB_HOST=dokku-postgres-db
dokku config:set odoo DB_USER=postgres
dokku config:set odoo DB_PASSWORD=f22c80ed2d4d88eafacef691090311bd
```
But odoo could not run due to:
```
=====> odoo web container output:
       Using the database user 'postgres' is a security risk, aborting.Using the database user 'postgres' is a security risk, aborting.Using the database user 'postgres' is a security risk, aborting.Using the database user 'postgres' is a security risk, aborting.Using the database user 'postgres' is a security risk, aborting.Using the database user 'postgres' is a security risk, aborting.
=====> end odoo web container output
To dokku.odoo.md:odoo
 ! [remote rejected] master -> master (pre-receive hook declined)
```

So I set 
```
dokku config:set odoo DB_USER=odoo
dokku config:set odoo DB_PASSWORD=odoo
```
Now entered the odoo_db docker container and added manually the odoo account:
```
docker exec -it 2188c5c4b2c5 bash
su - postgres
psql
CREATE USER odoo with password 'odoo' CREATEDB;
\q
exit
```

After that all worked as expected. Please update your docs.

**Comment by bfontaine** [comment]
Instead of creating the user by hand, you can create the Postgres container with a different user: https://github.com/dokku/dokku-postgres?tab=readme-ov-file#create-a-postgres-service
